### ISSUE TITLE
Cover TODO Next-Step Material Across Documentation 

### ISSUE THREAD

**Issue by O957** [CDCgov/multisignal-epi-inference#78]
## Goal

Cover the `TODO`s previously specified across documentation files. 

## Context

With first-pass documentation (#47) maturing, a noteworthy point brought up by DHM concerned the presence of `TODO`s in the `Notes` sections of the docstrings. These were out of place, given the issue, but still somewhat important to address for enhancing the richness of the documentation. As such, these `TODO`s have been aggregated here. Expect some changes to this issue's contents as the `TODO`s are ported over.  

## Specifications

This checklist covers the historical `TODO`s in each file: 

- [ ] Latent Folder
  - [ ] Add Notes in `class HospAdmissionsSample` in `hospitaladmissions.py`
  - [ ] Add Notes in `class InfectHospRateSample` in `hospitaladmissions.py`
  - [ ] Complete method `validate()` in `infections.py`
- [ ] Model Folder
  - [ ] Add See Also in `def __init__()` in `class HospitalizationModel(Model)` in `hospitalizations.py`
  - [ ] Add Examples in `def sample_hospitalizations_latent()` in `class HospitalizationModel(Model)` in `hospitalizations.py`
  - [ ] Add Examples in `def sample_hospitalizations_obs()` in `class HospitalizationModel(Model)` in `hospitalizations.py` 
  - [ ] Add Examples in `def sample_infections_obs()` in `class RtInfectionsRenewalModel(Model)` in `rtinfectionsrenewal.py`
  - [ ] Add See Also in `def sample()` in `class RtInfectionsRenewalModel(Model)` in `rtinfectionsrenewal.py`
- [ ] Top Level Folder (`pyrenew`)
  - [ ] Add Examples in file docstring for `convolve.py`
  - [ ] `convolve.py`, `new_convolve_scanner`: Add Examples section.
  - [ ] `convolve.py`, `new_convolve_scanner`: Expand and or verify Returns section. 

The remainder will be filled in w/ the completion of the corresponding PRs and issue 47. 

Reference the files here (produced with ` tree | grep -Ev "\.png|\.pyc|\.txt|\.csv|\.doctree|\.rst"`:

```
.
├── pyrenew
│   ├── convolve.py
│   ├── datasets
│   │   ├── __init__.py
│   │   ├── data-raw
│   │   │   ├── README.md
│   │   │   ├── generation_interval.py
│   │   │   ├── infection_admission_interval.py
│   │   │   └── wastewater.R
│   │   ├── generation_interval.py
│   │   ├── generation_interval.tsv
│   │   ├── infection_admission_interval.py
│   │   ├── infection_admission_interval.tsv
│   │   ├── wastewater.py
│   │   └── wastewater.tsv
│   ├── deterministic
│   │   ├── __init__.py
│   │   ├── deterministic.py
│   │   ├── deterministicpmf.py
│   │   └── process.py
│   ├── distutil.py
│   ├── latent
│   │   ├── __init__.py
│   │   ├── hospitaladmissions.py
│   │   ├── i0.py
│   │   ├── infection_functions.py
│   │   └── infections.py
│   ├── math.py
│   ├── mcmcutils.py
│   ├── metaclass.py
│   ├── model
│   │   ├── __init__.py
│   │   ├── hospitalizations.py
│   │   └── rtinfectionsrenewal.py
│   ├── observation
│   │   ├── __init__.py
│   │   ├── negativebinomial.py
│   │   └── poisson.py
│   ├── process
│   │   ├── __init__.py
│   │   ├── ar.py
│   │   ├── firstdifferencear.py
│   │   ├── rtrandomwalk.py
│   │   └── simplerandomwalk.py
│   ├── regression.py
│   └── transform.py
└── test
    ├── __init__.py
    ├── baseline
    ├── test_ar_process.py
    ├── test_datasets.py
    ├── test_deterministic.py
    ├── test_first_difference_ar.py
    ├── test_latent_hospitalizations.py
    ├── test_latent_infections.py
    ├── test_leslie_matrix.py
    ├── test_logistic_susceptibility_adjustment.py
    ├── test_model_basic_renewal.py
    ├── test_model_hospitalizations.py
    ├── test_observation_negativebinom.py
    ├── test_observation_poisson.py
    ├── test_process_asymptotics.py
    ├── test_random_walk.py
    ├── test_regression.py
    └── test_transforms.py

10 directories, 56 files
```

## Related Documents

- PR for top-level folder files documentation: [pending]
- PR for latent folder documentation: #73 
- PR for model folder documentation: #74 
- PR for process folder documentation: [pending]
- PR for observation folder documentation: #76 
- PR for deterministic folder documentation: [pending]
- PR for quarto docs documentation: #77
